# Generated by Django 4.2.5 on 2023-11-10 15:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('main', '0001_initial'),
        ('students_admin', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('teachers_admin', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Alumni',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(default='/static/admin/assets/images/logo-mobile.png', upload_to='')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('diploma', models.CharField(blank=True, max_length=255, null=True)),
                ('diploma_year', models.IntegerField(blank=True, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='CalendrierAcademique',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('annee_scolaire', models.CharField(max_length=10)),
                ('date_debut_semestre1', models.DateField()),
                ('date_fin_semestre1', models.DateField()),
                ('date_debut_semestre2', models.DateField()),
                ('date_fin_semestre2', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('faculty', models.CharField(choices=[('Philosophie', 'philosophie'), ('Ingeniérie', 'Ingeniérie'), ('Agronomiques et Vetérinaires', 'Agronomiques et Vetérinaires'), ('Général', 'Général')], max_length=255)),
                ('title', models.CharField(max_length=255)),
                ('image', models.ImageField(default='/static/admin/assets/images/logo-mobile.png', upload_to='')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='note')),
                ('pdf_files', models.FileField(upload_to='cours_pdfs/')),
                ('description', models.TextField(blank=True, null=True)),
                ('date_of_register', models.DateTimeField(auto_now_add=True)),
                ('category', models.CharField(max_length=100)),
                ('view', models.PositiveIntegerField(default=0)),
                ('data', models.JSONField(blank=True, null=True)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('auditoire', models.ManyToManyField(related_name='course_auditoire', to='main.niveau_d_etude')),
                ('teacher', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='teachers_admin.teacher')),
            ],
        ),
        migrations.CreateModel(
            name='NewletterEmail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='TeacherStudentRelation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Teacher', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='teachers', to='teachers_admin.teacher')),
                ('student', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='students', to='students_admin.student')),
            ],
        ),
        migrations.CreateModel(
            name='StudentCourses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('auditoire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.niveau_d_etude')),
                ('courses', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='university_admin.course')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_courses', to='students_admin.student')),
            ],
        ),
        migrations.CreateModel(
            name='Registration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=45)),
                ('last_name', models.CharField(max_length=45)),
                ('year_of_added', models.CharField(blank=True, max_length=255, null=True)),
                ('faculty', models.CharField(choices=[('Philosophie', 'philosophie'), ('Ingeniérie', 'Ingeniérie'), ('Agronomiques et Vetérinaires', 'Agronomiques et Vetérinaires'), ('Général', 'Général')], max_length=255)),
                ('registration_date', models.DateTimeField(auto_now_add=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('data', models.JSONField(blank=True, null=True)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='student_registration', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
