# Generated by Django 4.2.5 on 2023-11-11 17:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('university_admin', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Registration',
        ),
    ]
