# Generated by Django 4.2.5 on 2023-10-03 12:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
        ('university_admin', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pdfcourse',
            name='audience',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.audience'),
        ),
        migrations.AddField(
            model_name='studentcourses',
            name='audience',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='main.audience'),
            preserve_default=False,
        ),
    ]
