# Generated by Django 5.1.2 on 2025-02-23 18:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachers_admin', '0002_alter_teacher_options_alter_teacher_born_date_and_more'),
        ('university_admin', '0002_delete_registration'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='course',
            options={'verbose_name': 'Cours', 'verbose_name_plural': 'Cours'},
        ),
        migrations.AlterModelOptions(
            name='studentcourses',
            options={'verbose_name': "Cours d'etudiant", 'verbose_name_plural': "Cours d'etudiants"},
        ),
        migrations.AlterField(
            model_name='course',
            name='faculty',
            field=models.CharField(choices=[('Philosophie', 'philosophie'), ('Ingeniérie', 'Ingeniérie'), ('Agronomiques et Vetérinaires', 'Agronomiques et Vetérinaires'), ('Général', 'Général')], max_length=255, verbose_name='Faculté'),
        ),
        migrations.AlterField(
            model_name='course',
            name='pdf_files',
            field=models.FileField(upload_to='cours_pdfs/', verbose_name='Fichiers pdf'),
        ),
        migrations.AlterField(
            model_name='course',
            name='teacher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='teachers_admin.teacher', verbose_name='Professeur'),
        ),
        migrations.AlterField(
            model_name='course',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Titre'),
        ),
    ]
