# Generated by Django 4.2.5 on 2023-10-03 14:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('university_admin', '0002_pdfcourse_audience_studentcourses_audience'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pdfcourse',
            old_name='audience',
            new_name='auditoire',
        ),
        migrations.RenameField(
            model_name='studentcourses',
            old_name='audience',
            new_name='auditoire',
        ),
    ]
