# Generated by Django 4.2.5 on 2023-10-03 15:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auditoire_slug'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('teachers_admin', '0002_teacher_slug'),
        ('university_admin', '0003_rename_audience_pdfcourse_auditoire_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pdfcourse',
            name='auditoire',
        ),
        migrations.RemoveField(
            model_name='pdfcourse',
            name='teacher',
        ),
        migrations.RemoveField(
            model_name='registration',
            name='student',
        ),
        migrations.AddField(
            model_name='registration',
            name='first_name',
            field=models.CharField(default='', max_length=45),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='registration',
            name='last_name',
            field=models.CharField(default='', max_length=45),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='registration',
            name='option',
            field=models.CharField(choices=[('Philosophe', 'philosophie'), ('ingeniérie', 'ingeniérie'), ('Agronomiques et Vetérinaires', 'Agronomiques et Vetérinaires')], default='', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='registration',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='student_registration', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='registration',
            name='year_of_added',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('warning', models.TextField(blank=True, null=True, verbose_name='avertissement')),
                ('pdf_files', models.FileField(upload_to='cours_pdfs/')),
                ('date_of_register', models.DateTimeField(auto_now_add=True)),
                ('data', models.JSONField(blank=True, null=True)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('auditoire', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='course_auditoire', to='main.auditoire')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teachers_admin.teacher')),
            ],
        ),
        migrations.AlterField(
            model_name='studentcourses',
            name='courses',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='university_admin.course'),
        ),
    ]
