# Generated by Django 4.2.5 on 2023-10-03 15:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_auditoire_course_alter_auditoire_teachers'),
        ('university_admin', '0004_remove_pdfcourse_auditoire_remove_pdfcourse_teacher_and_more'),
        ('students_admin', '0004_alter_studentcourses_courses'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PdfCourse',
        ),
    ]
