# Generated by Django 4.2.5 on 2023-10-03 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('university_admin', '0005_delete_pdfcourse'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='category',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='course',
            name='view',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
