# Generated by Django 4.2.5 on 2023-10-03 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_auditoire_course_alter_auditoire_teachers'),
        ('university_admin', '0006_course_category_course_view'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='auditoire',
        ),
        migrations.AddField(
            model_name='course',
            name='auditoire',
            field=models.ManyToManyField(related_name='course_auditoire', to='main.auditoire'),
        ),
    ]
