# Generated by Django 4.2.5 on 2023-10-03 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('university_admin', '0007_remove_course_auditoire_course_auditoire'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
