# Generated by Django 4.2.5 on 2023-10-03 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('university_admin', '0008_course_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='image',
            field=models.ImageField(default='', upload_to=''),
            preserve_default=False,
        ),
    ]
