# Generated by Django 4.2.5 on 2023-10-04 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('university_admin', '0009_course_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='warning',
        ),
        migrations.AddField(
            model_name='course',
            name='notes',
            field=models.TextField(blank=True, null=True, verbose_name='note'),
        ),
        migrations.AlterField(
            model_name='course',
            name='image',
            field=models.ImageField(default='/static/admin/assets/images/logo-mobile.png', upload_to=''),
        ),
    ]
