# Generated by Django 4.2.5 on 2023-10-05 13:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_faculty'),
        ('university_admin', '0010_remove_course_warning_course_notes_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registration',
            name='option',
        ),
        migrations.AddField(
            model_name='registration',
            name='faculty',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.faculty'),
        ),
    ]
