# Generated by Django 4.2.5 on 2023-10-05 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('university_admin', '0011_remove_registration_option_registration_faculty'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='faculty',
            field=models.CharField(choices=[('Philosophe', 'philosophie'), ('ingeniérie', 'ingeniérie'), ('Agronomiques et Vetérinaires', 'Agronomiques et Vetérinaires')], default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='registration',
            name='faculty',
            field=models.CharField(choices=[('Philosophe', 'philosophie'), ('ingeniérie', 'ingeniérie'), ('Agronomiques et Vetérinaires', 'Agronomiques et Vetérinaires')], default='', max_length=255),
            preserve_default=False,
        ),
    ]
