# Generated by Django 4.2.5 on 2023-10-07 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('university_admin', '0012_course_faculty_alter_registration_faculty'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='faculty',
            field=models.CharField(choices=[('Philosophie', 'philosophie'), ('ingeniérie', 'ingeniérie'), ('Agronomiques et Vetérinaires', 'Agronomiques et Vetérinaires')], max_length=255),
        ),
        migrations.AlterField(
            model_name='registration',
            name='faculty',
            field=models.CharField(choices=[('Philosophie', 'philosophie'), ('ingeniérie', 'ingeniérie'), ('Agronomiques et Vetérinaires', 'Agronomiques et Vetérinaires')], max_length=255),
        ),
    ]
