# Generated by Django 4.2.5 on 2023-10-10 16:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('teachers_admin', '0008_teacher_first_name_teacher_last_name'),
        ('university_admin', '0014_alumni_course_is_deleted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='teacher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='teachers_admin.teacher'),
        ),
    ]
