# Generated by Django 4.2.5 on 2023-10-12 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('university_admin', '0015_alter_course_teacher'),
    ]

    operations = [
        migrations.AddField(
            model_name='alumni',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
