# Generated by Django 4.2.5 on 2023-10-17 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('university_admin', '0016_alumni_is_deleted'),
    ]

    operations = [
        migrations.AddField(
            model_name='alumni',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='alumni',
            name='image',
            field=models.ImageField(default='/static/admin/assets/images/logo-mobile.png', upload_to=''),
        ),
        migrations.AlterField(
            model_name='alumni',
            name='diploma',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='alumni',
            name='diploma_year',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='alumni',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
