# Generated by Django 4.2.5 on 2023-10-19 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('university_admin', '0017_alumni_description_alumni_image_alter_alumni_diploma_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='faculty',
            field=models.CharField(choices=[('Philosophie', 'philosophie'), ('Ingeniérie', 'Ingeniérie'), ('Agronomiques et Vetérinaires', 'Agronomiques et Vetérinaires')], max_length=255),
        ),
        migrations.AlterField(
            model_name='registration',
            name='faculty',
            field=models.CharField(choices=[('Philosophie', 'philosophie'), ('Ingeniérie', 'Ingeniérie'), ('Agronomiques et Vetérinaires', 'Agronomiques et Vetérinaires')], max_length=255),
        ),
    ]
