# Generated by Django 4.2.5 on 2023-11-10 15:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, max_length=45, null=True)),
                ('last_name', models.CharField(blank=True, max_length=45, null=True)),
                ('username', models.CharField(blank=True, max_length=20, null=True, verbose_name="Nom d'utilisateur")),
                ('email', models.EmailField(blank=True, max_length=254, null=True, unique=True, verbose_name='email address')),
                ('phone', models.CharField(blank=True, max_length=50, null=True)),
                ('country', models.CharField(blank=True, max_length=100, null=True)),
                ('sexe_type', models.CharField(choices=[('M', 'M'), ('F', 'F')], default='Male', max_length=23)),
                ('is_delete', models.BooleanField(blank=True, default=False, null=True)),
                ('born_date', models.DateField(blank=True, null=True)),
                ('address', models.CharField(blank=True, max_length=70, null=True)),
                ('courses', models.CharField(blank=True, max_length=50, null=True)),
                ('data', models.JSONField(blank=True, null=True)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user_teacher', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
