# Generated by Django 5.1.2 on 2025-02-23 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachers_admin', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='teacher',
            options={'verbose_name': 'Professeur', 'verbose_name_plural': 'Professeurs'},
        ),
        migrations.AlterField(
            model_name='teacher',
            name='born_date',
            field=models.DateField(blank=True, null=True, verbose_name="Date d'anniversaire"),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='courses',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Cours'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='first_name',
            field=models.CharField(blank=True, max_length=45, null=True, verbose_name='Prenom'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='last_name',
            field=models.CharField(blank=True, max_length=45, null=True, verbose_name='Nom'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='sexe_type',
            field=models.CharField(choices=[('M', 'M'), ('F', 'F')], default='Male', max_length=23, verbose_name='Sexe'),
        ),
    ]
