# Generated by Django 4.2.5 on 2023-10-05 11:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teachers_admin', '0002_teacher_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacher',
            name='courses',
        ),
    ]
