# Generated by Django 4.2.5 on 2023-10-08 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachers_admin', '0006_teacher_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='username',
            field=models.CharField(max_length=20, verbose_name="Nom d'utilisateur"),
        ),
    ]
