# Generated by Django 4.2.5 on 2023-10-08 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachers_admin', '0007_alter_teacher_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='first_name',
            field=models.CharField(default='', max_length=45),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='teacher',
            name='last_name',
            field=models.CharField(default='', max_length=45),
            preserve_default=False,
        ),
    ]
