# Generated by Django 4.2.5 on 2023-11-10 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_alter_new_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='new',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='date'),
        ),
    ]
