# Generated by Django 4.2.5 on 2023-11-10 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_alter_new_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='new',
            name='category',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='new',
            name='title',
            field=models.CharField(max_length=500),
        ),
    ]
