# Generated by Django 5.1.2 on 2025-02-23 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_alter_new_category_alter_new_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='new',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='news_videos/'),
        ),
        migrations.AddField(
            model_name='new',
            name='video_url',
            field=models.URLField(blank=True, help_text='Lien YouTube ou Vimeo', null=True),
        ),
    ]
