# Generated by Django 5.1.2 on 2025-02-23 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_new_video_new_video_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='new',
            name='sub_title',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
