# Generated by Django 5.1.2 on 2025-02-24 15:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_new_sub_title'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='new',
            options={'verbose_name': 'Article', 'verbose_name_plural': 'Articles'},
        ),
        migrations.AlterField(
            model_name='new',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_author', to=settings.AUTH_USER_MODEL, verbose_name='Auteur'),
        ),
        migrations.AlterField(
            model_name='new',
            name='category',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Catégorie'),
        ),
        migrations.AlterField(
            model_name='new',
            name='content',
            field=models.TextField(verbose_name='Contenu'),
        ),
        migrations.AlterField(
            model_name='new',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Date de création'),
        ),
        migrations.AlterField(
            model_name='new',
            name='data',
            field=models.JSONField(blank=True, null=True, verbose_name='Données supplémentaires'),
        ),
        migrations.AlterField(
            model_name='new',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='news_images/', verbose_name='Image principale'),
        ),
        migrations.AlterField(
            model_name='new',
            name='image1',
            field=models.ImageField(blank=True, null=True, upload_to='news_images/', verbose_name='Image 1'),
        ),
        migrations.AlterField(
            model_name='new',
            name='image2',
            field=models.ImageField(blank=True, null=True, upload_to='news_images/', verbose_name='Image 2'),
        ),
        migrations.AlterField(
            model_name='new',
            name='image3',
            field=models.ImageField(blank=True, null=True, upload_to='news_images/', verbose_name='Image 3'),
        ),
        migrations.AlterField(
            model_name='new',
            name='image4',
            field=models.ImageField(blank=True, null=True, upload_to='news_images/', verbose_name='Image 4'),
        ),
        migrations.AlterField(
            model_name='new',
            name='image5',
            field=models.ImageField(blank=True, null=True, upload_to='news_images/', verbose_name='Image 5'),
        ),
        migrations.AlterField(
            model_name='new',
            name='image6',
            field=models.ImageField(blank=True, null=True, upload_to='news_images/', verbose_name='Image 6'),
        ),
        migrations.AlterField(
            model_name='new',
            name='is_deleted',
            field=models.BooleanField(default=False, verbose_name='Supprimé ?'),
        ),
        migrations.AlterField(
            model_name='new',
            name='sub_title',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Sous-titre'),
        ),
        migrations.AlterField(
            model_name='new',
            name='title',
            field=models.CharField(max_length=500, verbose_name='Titre'),
        ),
        migrations.AlterField(
            model_name='new',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='news_videos/', verbose_name='Vidéo'),
        ),
        migrations.AlterField(
            model_name='new',
            name='video_url',
            field=models.URLField(blank=True, help_text='Lien YouTube ou Vimeo', null=True, verbose_name='URL de la vidéo'),
        ),
        migrations.AlterField(
            model_name='new',
            name='views',
            field=models.PositiveIntegerField(default=0, editable=False),
        ),
    ]
