# Generated by Django 4.2.5 on 2023-10-03 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('teachers_admin', '0001_initial'),
        ('university_admin', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Audience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('niveau_name', models.CharField(blank=True, max_length=50)),
                ('data', models.JSONField(blank=True, null=True)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('course', models.ManyToManyField(blank=True, related_name='audience_courses', to='university_admin.pdfcourse')),
                ('teachers', models.ManyToManyField(blank=True, null=True, related_name='audience_teachers', to='teachers_admin.teacher')),
            ],
        ),
    ]
