# Generated by Django 4.2.5 on 2023-10-03 14:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teachers_admin', '0001_initial'),
        ('university_admin', '0003_rename_audience_pdfcourse_auditoire_and_more'),
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Audience',
            new_name='Auditoire',
        ),
    ]
