# Generated by Django 4.2.5 on 2023-10-03 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_rename_audience_auditoire'),
    ]

    operations = [
        migrations.AddField(
            model_name='auditoire',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
    ]
