# Generated by Django 4.2.5 on 2023-10-03 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachers_admin', '0002_teacher_slug'),
        ('main', '0003_auditoire_slug'),
        ('university_admin', '0004_remove_pdfcourse_auditoire_remove_pdfcourse_teacher_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditoire',
            name='course',
            field=models.ManyToManyField(blank=True, related_name='auditoire_courses', to='university_admin.course'),
        ),
        migrations.AlterField(
            model_name='auditoire',
            name='teachers',
            field=models.ManyToManyField(blank=True, related_name='auditoire_teachers', to='teachers_admin.teacher'),
        ),
    ]
