# Generated by Django 4.2.5 on 2023-10-05 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_auditoire_course_alter_auditoire_teachers'),
    ]

    operations = [
        migrations.CreateModel(
            name='Faculty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('Philosophe', 'philosophie'), ('ingeniérie', 'ingeniérie'), ('Agronomiques et Vetérinaires', 'Agronomiques et Vetérinaires')], max_length=100)),
            ],
        ),
    ]
