# Generated by Django 4.2.5 on 2023-10-05 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_faculty'),
    ]

    operations = [
        migrations.AddField(
            model_name='auditoire',
            name='faculty',
            field=models.CharField(choices=[('Philosophe', 'philosophie'), ('ingeniérie', 'ingeniérie'), ('Agronomiques et Vetérinaires', 'Agronomiques et Vetérinaires')], default='', max_length=50),
            preserve_default=False,
        ),
    ]
