# Generated by Django 4.2.5 on 2023-10-07 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auditoire_faculty'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditoire',
            name='faculty',
            field=models.CharField(choices=[('Philosophie', 'philosophie'), ('ingeniérie', 'ingeniérie'), ('Agronomiques et Vetérinaires', 'Agronomiques et Vetérinaires')], max_length=50),
        ),
        migrations.AlterField(
            model_name='faculty',
            name='name',
            field=models.CharField(choices=[('Philosophie', 'philosophie'), ('ingeniérie', 'ingeniérie'), ('Agronomiques et Vetérinaires', 'Agronomiques et Vetérinaires')], max_length=100),
        ),
    ]
