# Generated by Django 4.2.5 on 2023-10-26 00:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_alter_auditoire_faculty_alter_faculty_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='auditoire',
            old_name='course',
            new_name='courses',
        ),
    ]
