# Generated by Django 4.2.5 on 2023-09-28 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userApp', '0002_remove_user_age_remove_user_city_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='sex_type',
            new_name='sexe_type',
        ),
        migrations.AddField(
            model_name='user',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
    ]
