# Generated by Django 4.2.5 on 2023-10-06 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userApp', '0004_user_is_student_user_is_teacher'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('professeur', 'professeur'), ('etudiant', 'etudiant')], default='', max_length=100),
            preserve_default=False,
        ),
    ]
