# Generated by Django 4.2.5 on 2023-10-07 11:36

from django.db import migrations, models
import userApp.models


class Migration(migrations.Migration):

    dependencies = [
        ('userApp', '0007_alter_user_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, default='userApp/university_mobile_logo_ulc-1 (1).png', null=True, upload_to=userApp.models.user_path),
        ),
    ]
