# Generated by Django 4.2.5 on 2023-10-10 16:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userApp', '0010_alter_user_username'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Alumni',
        ),
    ]
