# Generated by Django 4.2.5 on 2023-10-10 22:44

from django.db import migrations, models
import userApp.models


class Migration(migrations.Migration):

    dependencies = [
        ('userApp', '0011_delete_alumni'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, default='static/assets/images/university_mobile_logo_ulc-1.png', null=True, upload_to=userApp.models.user_path),
        ),
    ]
