# Generated by Django 4.2.5 on 2023-10-14 18:41

from django.db import migrations, models
import userApp.models


class Migration(migrations.Migration):

    dependencies = [
        ('userApp', '0013_alter_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, default='/static/defaultPerson.jpg', null=True, upload_to=userApp.models.user_path),
        ),
    ]
