# Generated by Django 4.2.5 on 2023-11-10 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachers_admin', '0001_initial'),
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='niveau_d_etude',
            name='teachers',
            field=models.ManyToManyField(blank=True, related_name='auditoire_teachers', to='teachers_admin.teacher'),
        ),
    ]
