# Generated by Django 4.2.5 on 2023-09-26 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year_of_added', models.CharField(blank=True, max_length=255, null=True)),
                ('option', models.CharField(max_length=200)),
                ('class_level', models.CharField(blank=True, max_length=50, null=True, verbose_name="niveau d'étude")),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('data', models.JSONField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='StudentCourses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
