# Generated by Django 4.2.5 on 2023-11-10 15:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
        ('students_admin', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='auditoire',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='auditoire_students', to='main.niveau_d_etude'),
        ),
    ]
