# Generated by Django 4.2.5 on 2023-11-10 15:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('university_admin', '0001_initial'),
        ('students_admin', '0002_student_auditoire'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentcourses',
            name='courses',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='courses', to='university_admin.course'),
            preserve_default=False,
        ),
    ]
