# Generated by Django 4.2.5 on 2023-10-03 15:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('students_admin', '0003_rename_date_student_date_joined_and_more'),
        ('university_admin', '0004_remove_pdfcourse_auditoire_remove_pdfcourse_teacher_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentcourses',
            name='courses',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='courses', to='university_admin.course'),
        ),
    ]
