# Generated by Django 4.2.5 on 2023-10-05 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students_admin', '0004_alter_studentcourses_courses'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='option',
        ),
        migrations.AddField(
            model_name='student',
            name='faculty',
            field=models.CharField(choices=[('Philosophe', 'philosophie'), ('ingeniérie', 'ingeniérie'), ('Agronomiques et Vetérinaires', 'Agronomiques et Vetérinaires')], default='', max_length=255),
            preserve_default=False,
        ),
    ]
