# Generated by Django 4.2.5 on 2023-11-11 19:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students_admin', '0006_student_auditoire'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='souscription',
            name='amount',
        ),
    ]
