# Generated by Django 4.2.5 on 2023-10-08 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students_admin', '0006_alter_student_faculty'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='username',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
    ]
