# Generated by Django 4.2.5 on 2023-11-14 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students_admin', '0007_remove_souscription_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='souscription',
            name='post_name',
            field=models.CharField(default='', max_length=45, verbose_name='Post-nom'),
            preserve_default=False,
        ),
    ]
