# Generated by Django 4.2.5 on 2023-10-14 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students_admin', '0008_alter_student_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='first_name',
            field=models.CharField(blank=True, max_length=45, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='last_name',
            field=models.CharField(blank=True, max_length=45, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='username',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name="Nom d'utilisateur"),
        ),
    ]
