# Generated by Django 4.2.5 on 2023-11-14 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students_admin', '0008_souscription_post_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='souscription',
            name='city',
            field=models.CharField(default='', max_length=45, verbose_name='Ville'),
            preserve_default=False,
        ),
    ]
