# Generated by Django 5.1.2 on 2025-02-23 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students_admin', '0009_souscription_city'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='student',
            options={'verbose_name': 'Etudiant', 'verbose_name_plural': 'Etudiants'},
        ),
        migrations.AlterField(
            model_name='souscription',
            name='sexe_type',
            field=models.CharField(max_length=334, verbose_name='sexe'),
        ),
        migrations.AlterField(
            model_name='student',
            name='address',
            field=models.CharField(blank=True, max_length=70, null=True, verbose_name='Adresse'),
        ),
        migrations.AlterField(
            model_name='student',
            name='born_date',
            field=models.DateField(blank=True, null=True, verbose_name="Date d'anniversaire"),
        ),
        migrations.AlterField(
            model_name='student',
            name='country',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Pays'),
        ),
        migrations.AlterField(
            model_name='student',
            name='faculty',
            field=models.CharField(choices=[('Philosophie', 'philosophie'), ('Ingeniérie', 'Ingeniérie'), ('Agronomiques et Vetérinaires', 'Agronomiques et Vetérinaires'), ('Général', 'Général')], max_length=255, verbose_name='Faculté'),
        ),
        migrations.AlterField(
            model_name='student',
            name='first_name',
            field=models.CharField(blank=True, max_length=45, null=True, verbose_name='Prenom'),
        ),
        migrations.AlterField(
            model_name='student',
            name='last_name',
            field=models.CharField(blank=True, max_length=45, null=True, verbose_name='Nom'),
        ),
        migrations.AlterField(
            model_name='student',
            name='sexe_type',
            field=models.CharField(blank=True, choices=[('M', 'M'), ('F', 'F')], default='Male', max_length=23, verbose_name='Sexe'),
        ),
    ]
