# Generated by Django 4.2.5 on 2023-10-14 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students_admin', '0010_alter_student_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, unique=True, verbose_name='email address'),
        ),
        migrations.AlterField(
            model_name='student',
            name='phone',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='sexe_type',
            field=models.CharField(blank=True, choices=[('M', 'M'), ('F', 'F')], default='Male', max_length=23),
        ),
    ]
