# Generated by Django 4.2.5 on 2023-10-18 11:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('students_admin', '0011_alter_student_email_alter_student_phone_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Souscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=45)),
                ('last_name', models.CharField(max_length=45)),
                ('year_of_added', models.CharField(blank=True, max_length=255, null=True)),
                ('faculty', models.CharField(choices=[('Philosophie', 'philosophie'), ('ingeniérie', 'ingeniérie'), ('Agronomiques et Vetérinaires', 'Agronomiques et Vetérinaires')], max_length=255)),
                ('registration_date', models.DateTimeField(auto_now_add=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('data', models.JSONField(blank=True, null=True)),
                ('student', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='student_registration', to='students_admin.student')),
            ],
        ),
    ]
