# Generated by Django 5.1.2 on 2025-02-28 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students_admin', '0011_souscription_avatar_souscription_document_file_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='souscription',
            name='is_paid',
            field=models.BooleanField(default=False, verbose_name='Les frais sont payés?'),
        ),
    ]
