# Generated by Django 4.2.5 on 2023-10-26 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students_admin', '0013_alter_souscription_faculty_alter_student_faculty'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='country',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
